name: Run SonarQube with Maven

on: push

permissions:
  issues: write  # This allows the workflow to create issues

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Build with Maven and SonarCloud
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=chamrouensqa_sonar-scanning-examples -Dsonar.organization=chamrouensqa -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
